################ BACKGROUND ################

background {
    monitor = 
    path = /home/amal/Pictures/Wallpaper/YoshikageKira0.png
    blur_passes = 0
    blur_size = 0
    brightness = 1.0
}

################ TIME ################

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 80
    font_family = arcadeclassic
    color = rgb(61,73,91)

    position = 200, 150
    halign = left
    valign = center
}

################ DATE ################

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A %d')"
    font_size = 18
    font_family = arcadeclassic
    color = rgb(61,73,91)

    position = 200, 100
    halign = left
    valign = center
}

################ PASSWORD FIELD ################

input-field {
    monitor =
    size = 350, 55
    outline_thickness = 0

    outer_color = rgb(61,73,91)
    inner_color = rgb(204,204,204)
    font_color = rgb(61,73,91)

    dots_size = 0.25
    dots_spacing = 0.35
    dots_center = true
    fade_on_empty = false
    placeholder_text = Password

    rounding = 20

    position = 200, -50
    halign = left
    valign = center
}
